/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the npm repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VideoNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  port: 8765,
  pythonPath: "~/obsidian-video-note/server/venv/bin/python",
  serverScript: "~/obsidian-video-note/server/main.py",
  saveFolder: "\u89C6\u9891\u7B14\u8BB0",
  claudeMode: "claude_cli",
  apiKey: "",
  claudeModel: "claude-sonnet-4-20250514",
  openaiApiKey: "",
  openaiModel: "gpt-4o-mini",
  whisperModel: "medium",
  includeRaw: true,
  cookies: "",
  autoStartServer: true,
  tags: "\u89C6\u9891\u7B14\u8BB0"
};
var VideoNoteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u89C6\u9891\u7B14\u8BB0\u52A9\u624B\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u672C\u5730\u670D\u52A1\u7AEF\u53E3").setDesc("\u672C\u5730 Python \u670D\u52A1\u76D1\u542C\u7684\u7AEF\u53E3\uFF0C\u4E00\u822C\u65E0\u9700\u4FEE\u6539").addText((t) => t.setValue(String(this.plugin.settings.port)).onChange(async (v) => {
      const n = parseInt(v, 10);
      if (!isNaN(n)) {
        this.plugin.settings.port = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Python \u89E3\u91CA\u5668\u8DEF\u5F84").setDesc("\u670D\u52A1 venv \u4E0B\u7684 python\uFF0C\u5982 ~/obsidian-video-note/server/venv/bin/python").addText((t) => t.setPlaceholder("~/obsidian-video-note/server/venv/bin/python").setValue(this.plugin.settings.pythonPath).onChange(async (v) => {
      this.plugin.settings.pythonPath = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u670D\u52A1\u811A\u672C\u8DEF\u5F84").setDesc("\u672C\u5730\u670D\u52A1 main.py \u7684\u5B8C\u6574\u8DEF\u5F84").addText((t) => t.setPlaceholder("~/obsidian-video-note/server/main.py").setValue(this.plugin.settings.serverScript).onChange(async (v) => {
      this.plugin.settings.serverScript = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u7B14\u8BB0\u4FDD\u5B58\u6587\u4EF6\u5939").setDesc("vault \u5185\u4FDD\u5B58\u89C6\u9891\u7B14\u8BB0\u7684\u6587\u4EF6\u5939\uFF0C\u4E0D\u5B58\u5728\u4F1A\u81EA\u52A8\u521B\u5EFA").addText((t) => t.setPlaceholder("\u89C6\u9891\u7B14\u8BB0").setValue(this.plugin.settings.saveFolder).onChange(async (v) => {
      this.plugin.settings.saveFolder = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u91CD\u6392\u5F15\u64CE\uFF08\u6574\u7406\u7B14\u8BB0\u7528\u54EA\u4E2A\u5927\u6A21\u578B\uFF09").setDesc("Claude Code / Codex CLI \u8D70\u5404\u81EA\u8BA2\u9605\u989D\u5EA6\uFF1BAPI \u6A21\u5F0F\u6309\u91CF\u4ED8\u8D39").addDropdown((d) => d.addOption("claude_cli", "Claude Code CLI\uFF08\u8BA2\u9605\uFF09").addOption("claude_api", "Claude API Key\uFF08\u6309\u91CF\uFF09").addOption("codex_cli", "Codex CLI\uFF08\u8BA2\u9605\uFF09").addOption("openai_api", "OpenAI API Key\uFF08\u6309\u91CF\uFF09").setValue(this.plugin.settings.claudeMode).onChange(async (v) => {
      this.plugin.settings.claudeMode = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Claude API Key").setDesc("\u4EC5 Claude API \u6A21\u5F0F\u9700\u8981\uFF0C\u5F62\u5982 sk-ant-\u2026").addText((t) => {
      t.setPlaceholder("sk-ant-\u2026").setValue(this.plugin.settings.apiKey).onChange(async (v) => {
        this.plugin.settings.apiKey = v.trim();
        await this.plugin.saveSettings();
      });
      t.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Claude \u6A21\u578B").setDesc("\u5982 claude-sonnet-4-20250514\uFF08CLI \u6A21\u5F0F\u53EF\u7528 --model \u8986\u76D6\uFF09").addText((t) => t.setValue(this.plugin.settings.claudeModel).onChange(async (v) => {
      this.plugin.settings.claudeModel = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("OpenAI API Key").setDesc("\u4EC5 OpenAI API \u6A21\u5F0F\u9700\u8981\uFF0C\u5F62\u5982 sk-\u2026").addText((t) => {
      t.setPlaceholder("sk-\u2026").setValue(this.plugin.settings.openaiApiKey).onChange(async (v) => {
        this.plugin.settings.openaiApiKey = v.trim();
        await this.plugin.saveSettings();
      });
      t.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("OpenAI \u6A21\u578B").setDesc("\u5982 gpt-4o-mini / gpt-4.1\uFF08Codex CLI \u6A21\u5F0F\u901A\u5E38\u65E0\u9700\u6539\uFF0C\u8D70\u5176\u9ED8\u8BA4\u6A21\u578B\uFF09").addText((t) => t.setValue(this.plugin.settings.openaiModel).onChange(async (v) => {
      this.plugin.settings.openaiModel = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Whisper \u6A21\u578B").setDesc("tiny/base/small/medium/large-v3\u3002\u8D8A\u5927\u8D8A\u51C6\u8D8A\u6162\uFF0C\u4E2D\u6587\u5EFA\u8BAE medium").addDropdown((d) => d.addOption("tiny", "tiny\uFF08\u6700\u5FEB\uFF09").addOption("base", "base").addOption("small", "small").addOption("medium", "medium\uFF08\u63A8\u8350\uFF09").addOption("large-v3", "large-v3\uFF08\u6700\u51C6\u6700\u6162\uFF09").setValue(this.plugin.settings.whisperModel).onChange(async (v) => {
      this.plugin.settings.whisperModel = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u7B14\u8BB0\u9644\u5E26\u539F\u59CB\u65C1\u767D").setDesc("\u5728\u7B14\u8BB0\u672B\u5C3E\u8FFD\u52A0\u5B8C\u6574\u7684\u5E26\u65F6\u95F4\u6233\u65C1\u767D").addToggle((t) => t.setValue(this.plugin.settings.includeRaw).onChange(async (v) => {
      this.plugin.settings.includeRaw = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("frontmatter \u6807\u7B7E").addText((t) => t.setValue(this.plugin.settings.tags).onChange(async (v) => {
      this.plugin.settings.tags = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6296\u97F3/\u5C0F\u7EA2\u4E66 Cookie").setDesc("\u6D4F\u89C8\u5668\u767B\u5F55\u5BF9\u5E94\u5E73\u53F0\u540E\uFF0C\u5728\u5F00\u53D1\u8005\u5DE5\u5177\u91CC\u590D\u5236 Cookie \u7C98\u8D34\u5230\u8FD9\u91CC\uFF08\u5206\u53F7\u5206\u9694\uFF0C\u5982 k1=v1; k2=v2\uFF09\u3002B\u7AD9\u65E0\u9700\u586B\u5199\u3002").addTextArea((t) => t.setPlaceholder("odin_tt=xxx; passport_csrf_token=yyy").setValue(this.plugin.settings.cookies).onChange(async (v) => {
      this.plugin.settings.cookies = v.trim();
      await this.plugin.saveSettings();
    }));
    (_a = containerEl.querySelector("textarea")) == null ? void 0 : _a.setAttribute("rows", "3");
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u62C9\u8D77\u672C\u5730\u670D\u52A1").setDesc("\u63D2\u4EF6\u52A0\u8F7D\u65F6\u81EA\u52A8\u542F\u52A8\u672C\u5730 Python \u670D\u52A1\uFF08\u5931\u8D25\u4F1A\u63D0\u793A\uFF09").addToggle((t) => t.setValue(this.plugin.settings.autoStartServer).onChange(async (v) => {
      this.plugin.settings.autoStartServer = v;
      await this.plugin.saveSettings();
    }));
  }
};

// src/serviceClient.ts
var import_child_process = require("child_process");
var import_os = require("os");
function expandHome(p) {
  if (!p) return p;
  if (p === "~") return (0, import_os.homedir)();
  if (p.startsWith("~/")) return (0, import_os.homedir)() + p.slice(1);
  return p;
}
var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function checkHealth(port, timeoutMs = 2500) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const resp = await fetch(`http://127.0.0.1:${port}/health`, { signal: controller.signal });
    return resp.ok;
  } catch (e) {
    return false;
  } finally {
    clearTimeout(timer);
  }
}
function startServer(pythonPath, scriptPath, port) {
  const child = (0, import_child_process.spawn)(expandHome(pythonPath), [expandHome(scriptPath), "--port", String(port)], {
    detached: true,
    stdio: "ignore"
  });
  child.on("error", (err) => {
    console.error("VideoNote: \u670D\u52A1\u542F\u52A8\u5931\u8D25", err);
  });
  child.unref();
}
async function waitForServer(port, waitMs = 3e4) {
  const start = Date.now();
  while (Date.now() - start < waitMs) {
    if (await checkHealth(port)) return true;
    await sleep(1e3);
  }
  return false;
}
async function submitJob(url, options, port) {
  const resp = await fetch(`http://127.0.0.1:${port}/jobs`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ url, options })
  });
  const data = await resp.json();
  if (!resp.ok) throw new Error(data.error || "\u63D0\u4EA4\u4EFB\u52A1\u5931\u8D25");
  return data.job_id;
}
async function fetchJob(port, jobId) {
  const resp = await fetch(`http://127.0.0.1:${port}/jobs/${jobId}`);
  if (resp.status === 404) {
    throw new Error("\u4EFB\u52A1\u5DF2\u4E0D\u5B58\u5728\uFF08\u670D\u52A1\u53EF\u80FD\u5DF2\u91CD\u542F\uFF09\uFF0C\u8BF7\u91CD\u65B0\u52A0\u5165\u961F\u5217");
  }
  return await resp.json();
}

// src/noteWriter.ts
var import_obsidian2 = require("obsidian");
function safeFilename(title) {
  const cleaned = (title || "\u89C6\u9891\u7B14\u8BB0").replace(/[\\/:*?"<>|#^[\]{}]/g, "-").replace(/\s+/g, " ").trim().slice(0, 80);
  return cleaned || "\u89C6\u9891\u7B14\u8BB0";
}
function buildMarkdown(meta, body, tags) {
  const date = (0, import_obsidian2.moment)().format("YYYY-MM-DD");
  const dur = meta.duration || 0;
  const platformNames = {
    bilibili: "B\u7AD9",
    douyin: "\u6296\u97F3",
    xiaohongshu: "\u5C0F\u7EA2\u4E66",
    youtube: "YouTube",
    unknown: "\u672A\u77E5"
  };
  return [
    "---",
    `\u5E73\u53F0: ${platformNames[meta.platform || "unknown"] || meta.platform}`,
    `\u6807\u9898: "${meta.title || ""}"`,
    `\u4F5C\u8005: "${meta.uploader || ""}"`,
    `\u6765\u6E90: ${meta.webpage_url || ""}`,
    `\u91C7\u96C6\u65E5\u671F: ${date}`,
    `\u65F6\u957F: ${Math.floor(dur / 60)}\u5206${dur % 60}\u79D2`,
    `\u6807\u7B7E: ["${tags}"]`,
    "---",
    "",
    body.trim(),
    ""
  ].join("\n");
}
async function ensureFolder(app, folder) {
  const normalized = (0, import_obsidian2.normalizePath)(folder);
  if (normalized && !app.vault.getAbstractFileByPath(normalized)) {
    await app.vault.createFolder(normalized);
  }
}
async function writeNote(app, folder, filename, content) {
  await ensureFolder(app, folder);
  const base = folder ? `${(0, import_obsidian2.normalizePath)(folder)}/${filename}` : filename;
  let path = base;
  let i = 1;
  while (app.vault.getAbstractFileByPath(path)) {
    const dot = base.lastIndexOf(".");
    path = dot > 0 ? `${base.slice(0, dot)}-${i}${base.slice(dot)}` : `${base}-${i}`;
    i++;
  }
  return app.vault.create(path, content);
}

// src/queue.ts
function fmtEta(s) {
  const m = Math.floor(s / 60);
  const sec = Math.round(s % 60);
  if (m > 0) return `${m} \u5206 ${sec} \u79D2`;
  return `${sec} \u79D2`;
}
function genId() {
  return Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8);
}

// src/queueView.ts
var import_obsidian3 = require("obsidian");
var QUEUE_VIEW_TYPE = "video-note-queue";
var STATUS_LABEL = {
  queued: "\u6392\u961F\u4E2D",
  running: "\u5904\u7406\u4E2D",
  done: "\u2705 \u5B8C\u6210",
  error: "\u274C \u5931\u8D25"
};
var QueueView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return QUEUE_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u89C6\u9891\u7B14\u8BB0\u961F\u5217";
  }
  getIcon() {
    return "video";
  }
  async onOpen() {
    this.plugin.queueView = this;
    const c = this.contentEl;
    c.empty();
    c.createEl("h4", { text: "\u89C6\u9891\u7B14\u8BB0\u961F\u5217" });
    this.inputEl = c.createEl("textarea", {
      attr: {
        placeholder: "\u7C98\u8D34\u89C6\u9891\u94FE\u63A5\uFF0C\u6BCF\u884C\u4E00\u4E2A\uFF08B\u7AD9/\u6296\u97F3/\u5C0F\u7EA2\u4E66\uFF09\nhttps://www.bilibili.com/video/\u2026\nhttps://xhslink.com/\u2026",
        rows: "3",
        style: "width: 100%; font-family: monospace;"
      }
    });
    const inputActions = c.createEl("div", { cls: "vnote-input-actions" });
    const addBtn = inputActions.createEl("button", { text: "\u52A0\u5165\u961F\u5217", cls: "vnote-primary" });
    addBtn.addEventListener("click", () => {
      const urls = this.inputEl.value.split("\n").map((s) => s.trim()).filter(Boolean);
      if (urls.length === 0) {
        new import_obsidian3.Notice("\u8BF7\u5148\u7C98\u8D34\u81F3\u5C11\u4E00\u4E2A\u89C6\u9891\u94FE\u63A5");
        return;
      }
      this.inputEl.value = "";
      void this.plugin.addToQueue(urls);
    });
    const clearBtn = inputActions.createEl("button", { text: "\u6E05\u9664\u5DF2\u5B8C\u6210/\u5931\u8D25" });
    clearBtn.addEventListener("click", () => void this.plugin.clearFinished());
    c.createEl("div", {
      text: "\u63D0\u793A\uFF1A\u5904\u7406\u4E2D/\u6392\u961F\u7684\u4EFB\u52A1\u4E0D\u4F1A\u88AB\u6E05\u9664",
      cls: "vnote-input-hint"
    });
    this.listEl = c.createEl("div", { cls: "vnote-queue" });
    this.renderList();
  }
  /** 刷新面板（供轮询/操作后调用）：只重建列表，不清空输入框 */
  refresh() {
    if (this.listEl) this.renderList();
  }
  renderList() {
    this.listEl.empty();
    if (this.plugin.queue.length === 0) {
      this.listEl.createEl("div", { text: "\u6682\u65E0\u4EFB\u52A1\u3002\u7C98\u8D34\u94FE\u63A5\u540E\u70B9\u300C\u52A0\u5165\u961F\u5217\u300D\u3002", cls: "vnote-empty" });
    }
    for (const item of this.plugin.queue) {
      this.renderItem(this.listEl, item);
    }
  }
  renderItem(parent, item) {
    var _a, _b, _c;
    const card = parent.createEl("div", { cls: "vnote-queue-item" });
    const title = item.title && item.title !== item.url ? item.title : item.url;
    card.createEl("div", { text: title, cls: "vnote-item-title" });
    const statusText = `${(_a = STATUS_LABEL[item.status]) != null ? _a : item.status} \xB7 ${item.progress || ""}`;
    card.createEl("div", { text: statusText, cls: "vnote-item-status" });
    if (item.status === "queued" || item.status === "running") {
      card.createEl("progress", {
        attr: { max: "100", value: String((_b = item.percent) != null ? _b : 0), style: "width: 100%;" }
      });
      let etaText = `${Math.round((_c = item.percent) != null ? _c : 0)}%`;
      if (item.eta && item.eta > 0) etaText += ` \xB7 \u9884\u8BA1\u5269\u4F59 ${fmtEta(item.eta)}`;
      card.createEl("div", { text: etaText, cls: "vnote-item-eta" });
    }
    if (item.error) {
      card.createEl("div", { text: item.error, cls: "vnote-item-error" });
    }
    if (item.notePath || item.status === "done" || item.status === "error") {
      const actions = card.createEl("div", { cls: "vnote-item-actions" });
      if (item.notePath) {
        const openBtn = actions.createEl("button", { text: "\u6253\u5F00\u7B14\u8BB0" });
        openBtn.addEventListener("click", () => void this.plugin.openNote(item.notePath));
      }
      if (item.status === "done" || item.status === "error") {
        const delBtn = actions.createEl("button", { text: "\u5220\u9664" });
        delBtn.addEventListener("click", () => void this.plugin.removeItem(item.id));
      }
    }
  }
  async onClose() {
    this.plugin.queueView = null;
  }
};

// src/main.ts
var VideoNotePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.queue = [];
    this.queueView = null;
    this.pollTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(QUEUE_VIEW_TYPE, (leaf) => new QueueView(leaf, this));
    this.addRibbonIcon("video", "\u89C6\u9891\u7B14\u8BB0\u52A9\u624B\uFF1A\u6253\u5F00\u4EFB\u52A1\u961F\u5217", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "video-to-note",
      name: "\u6253\u5F00\u89C6\u9891\u7B14\u8BB0\u961F\u5217",
      callback: () => void this.activateView()
    });
    this.addSettingTab(new VideoNoteSettingTab(this.app, this));
    if (this.settings.autoStartServer) {
      void this.ensureServer();
    }
    this.ensurePolling();
  }
  onunload() {
    if (this.pollTimer != null) {
      window.clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
  }
  async loadSettings() {
    var _a, _b;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : data);
    this.queue = (_b = data == null ? void 0 : data.queue) != null ? _b : [];
  }
  async saveSettings() {
    const payload = { settings: this.settings, queue: this.queue };
    await this.saveData(payload);
  }
  async persistQueue() {
    await this.saveSettings();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(QUEUE_VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeftLeaf(false);
      await leaf.setViewState({ type: QUEUE_VIEW_TYPE, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
  async ensureServer() {
    if (await checkHealth(this.settings.port)) return true;
    startServer(this.settings.pythonPath, this.settings.serverScript, this.settings.port);
    const ok = await waitForServer(this.settings.port);
    if (!ok) {
      new import_obsidian4.Notice("\u672C\u5730\u670D\u52A1\u542F\u52A8\u5931\u8D25\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u68C0\u67E5 Python / \u670D\u52A1\u811A\u672C\u8DEF\u5F84");
    }
    return ok;
  }
  buildOptions() {
    return {
      claude_mode: this.settings.claudeMode,
      api_key: this.settings.apiKey,
      claude_model: this.settings.claudeModel,
      openai_api_key: this.settings.openaiApiKey,
      openai_model: this.settings.openaiModel,
      whisper_model: this.settings.whisperModel,
      include_raw: this.settings.includeRaw,
      cookies: this.settings.cookies
    };
  }
  async addToQueue(urls) {
    var _a;
    const valid = urls.filter((u) => /^https?:\/\//i.test(u.trim()));
    if (valid.length === 0) {
      new import_obsidian4.Notice("\u6CA1\u6709\u6709\u6548\u7684\u94FE\u63A5\uFF08\u9700\u4EE5 http:// \u6216 https:// \u5F00\u5934\uFF09");
      return;
    }
    for (const url of valid) {
      const item = {
        id: genId(),
        url: url.trim(),
        title: url.trim(),
        platform: "",
        status: "queued",
        progress: "\u6392\u961F\u4E2D",
        percent: 0,
        eta: null,
        jobId: null,
        notePath: null,
        error: null,
        createdAt: Date.now()
      };
      this.queue.unshift(item);
    }
    await this.persistQueue();
    (_a = this.queueView) == null ? void 0 : _a.refresh();
    await this.kick();
  }
  /** 把排队中的任务提交到本地服务（服务端串行处理，天然排队） */
  async kick() {
    var _a;
    if (!await this.ensureServer()) return;
    for (const item of this.queue) {
      if (item.status === "queued" && !item.jobId) {
        try {
          item.jobId = await submitJob(item.url, this.buildOptions(), this.settings.port);
          item.progress = "\u5DF2\u63D0\u4EA4\uFF0C\u7B49\u5F85\u5904\u7406";
        } catch (e) {
          item.status = "error";
          item.error = e.message;
        }
      }
    }
    await this.persistQueue();
    (_a = this.queueView) == null ? void 0 : _a.refresh();
    this.ensurePolling();
  }
  ensurePolling() {
    if (this.pollTimer != null) return;
    this.pollTimer = window.setInterval(() => void this.pollAll(), 2e3);
    this.registerInterval(this.pollTimer);
  }
  async pollAll() {
    var _a, _b, _c;
    const active = this.queue.filter(
      (q) => q.jobId && (q.status === "queued" || q.status === "running")
    );
    if (active.length === 0) return;
    let changed = false;
    for (const item of active) {
      try {
        const d = await fetchJob(this.settings.port, item.jobId);
        item.progress = (_a = d.progress) != null ? _a : item.progress;
        if (d.percent != null) item.percent = d.percent;
        if (d.eta != null) item.eta = d.eta;
        if (d.status === "done") {
          item.status = "done";
          item.progress = "\u5B8C\u6210";
          item.percent = 100;
          item.eta = 0;
          await this.finishItem(item, d);
        } else if (d.status === "error") {
          item.status = "error";
          item.error = (_b = d.error) != null ? _b : "\u5904\u7406\u5931\u8D25";
        } else {
          item.status = "running";
        }
        changed = true;
      } catch (e) {
        if (item.status === "running" || item.status === "queued") {
          item.error = e.message;
        }
        changed = true;
      }
    }
    if (changed) {
      await this.persistQueue();
      (_c = this.queueView) == null ? void 0 : _c.refresh();
    }
  }
  async finishItem(item, d) {
    var _a, _b, _c, _d;
    if (item.notePath) return;
    try {
      const meta = (_b = (_a = d.result) == null ? void 0 : _a.meta) != null ? _b : {};
      const content = buildMarkdown(meta, (_d = (_c = d.result) == null ? void 0 : _c.markdown) != null ? _d : "", this.settings.tags);
      const file = await writeNote(
        this.app,
        this.settings.saveFolder,
        safeFilename(meta.title || "\u89C6\u9891\u7B14\u8BB0") + ".md",
        content
      );
      item.title = meta.title || item.url;
      item.platform = meta.platform || "";
      item.notePath = file.path;
    } catch (e) {
      item.status = "error";
      item.error = "\u7B14\u8BB0\u5199\u5165\u5931\u8D25\uFF1A" + e.message;
    }
  }
  async clearFinished() {
    var _a;
    this.queue = this.queue.filter((q) => q.status !== "done" && q.status !== "error");
    await this.persistQueue();
    (_a = this.queueView) == null ? void 0 : _a.refresh();
  }
  async removeItem(id) {
    var _a;
    this.queue = this.queue.filter((q) => q.id !== id);
    await this.persistQueue();
    (_a = this.queueView) == null ? void 0 : _a.refresh();
  }
  async openNote(path) {
    const f = this.app.vault.getAbstractFileByPath(path);
    if (f instanceof import_obsidian4.TFile) {
      await this.app.workspace.getLeaf(false).openFile(f);
    } else {
      new import_obsidian4.Notice("\u7B14\u8BB0\u6587\u4EF6\u4E0D\u5B58\u5728\uFF1A" + path);
    }
  }
};
